# image will be published to ghcr.io/<user>/<name>
name: hyprblu
# description will be included in the image's metadata
description: A personal image built atop 'ublue' using Hyprland

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same modul
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
                  
  - type: script
    scripts:
  - settheming.sh
  - addbrewjustimport.sh
  - removeunprofessionalwallpapers.sh
  - sethyprlandwaybarmodules.sh
  - setsddmtheming.sh
  
  - type: rpm-ostree
    install:
# launcher
  - rofi-wayland

# environment
  - power-profiles-daemon
  - xorg-x11-server-Xwayland
  - polkit
  - xfce-polkit 
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - wl-clipboard
  - pavucontrol
  - playerctl
  - qt5-qtwayland
  - qt6-qtwayland
  - vulkan-validation-layers
  - vulkan-tools
  - google-noto-emoji-fonts
  - gnome-disk-utility
  - ddcutil
  
# sound
  - wireplumber
  - pipewire
  - pamixer
  - pulseaudio-utils

# networking
  - network-manager-applet
  - NetworkManager-openvpn
  - NetworkManager-openconnect
  - bluez
  - bluez-tools
  - blueman

# file manager
  - thunar
  - thunar-archive-plugin 
  - thunar-volman
  - xarchiver
  - imv
  - p7zip
  - unrar
  - gvfs-mtp
  - gvfs-gphoto2
  - gvfs-smb
  - gvfs-nfs
  - gvfs-fuse
  - gvfs-archive
  - android-tools

# screenshot
  - slurp
  - grim

# display
  - wlr-randr
  - wlsunset
  - brightnessctl
  - swaylock
  - swayidle
  - kanshi

# terminal
  - foot

# notifications
  - dunst

# theme and GUI
  - adwaita-qt5
  - fontawesome-fonts-all
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme
  - breeze-icon-theme 
  - papirus-icon-theme
  
# hyprland
  - hyprland
  - waybar
  - xdg-desktop-portal-hyprland
  - brightnessctl

# sddm
  - sddm
  - sddm-themes
  - qt5-qtgraphicaleffects
  - qt5-qtquickcontrols2
  - qt5-qtsvg
  - kwallet
  - pam-kwallet
  
  
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - dunst
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: systemd
    system:
    enabled:
    - sddm-boot.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

